### ISSUE TITLE
NMEA output incorrect

### ISSUE THREAD

**Issue by DfAC** [TheGalfins/GNSS_Compare#2]
Your NMEA output format for lat long is incorrect. It should be DDMM.MMMMMM not DD.DDDDDD*100. Application reports values correctly on the screen so it is most likely a typo.

**Comment by mt-krainski** [comment]
Issue solved in the released version on Google Play. We will update the code here as soon as we have clearance for the new algorithms we're using.

**Comment by mt-krainski** [comment]
Issue solved
