### ISSUE TITLE
Do we have access to SAR in an android device?

### ISSUE THREAD

**Issue by TeTRA99** [TheGalfins/GNSS_Compare#6]
Can we trigger a SAR event using a Galileo-enabled android phone from the app?
Is it possible to do from our own apps?

**Comment by mt-krainski** [comment]
The SAR functionality requires specialised hardware. And by that I mean devices mounted on aircraft or bulky handheld devices bigger than a smartphone. I don't think it is technically possible, or even will be possible in foreseeable future, to trigger a SAR request from a regular smartphone.

**Comment by TeTRA99** [comment]
Pretty clear! Thanks for the quick answer!
